# test/_oracle_stepcontrol.jl -- Phase 4 oracle, pinned values.
#
# This file is auto-generated by:
#   external/probes/stepcontrol-oracle/verify.jl
# from three independent sources cross-checked to agree at Float64
# precision (and to 47 decimal digits for the high-precision pin):
#
#   oracles_julia.txt   <- TaylorIntegration.stepsize (canonical Julia)
#   oracles_python.txt  <- mpmath/sympy
#   oracles_wolfram.txt <- Mathematica
#
# Do NOT hand-edit.  Re-run capture.{jl,py,wl} + verify.jl to update;
# verify.jl asserts three-way agreement before writing.

# Phase 4 StepControl oracle (TI.jl primary).
# Captured by: julia --project=. capture.jl
# Format: Julia-readable literals (top-level assignments).

# Case 4.1.1 / 4.1.2 -- exp Taylor coefs c[k] = 1/k!, k=0..30; eps = 1e-12.
# Source: TaylorIntegration.stepsize(Taylor1(c, 30), 1e-12).
# Direct TI.jl output, 1e-15 round-trip precision:
h_4_1_1_TI = 4.501206370338986
coefs_4_1_1 = [1.0, 1.0, 0.5, 0.16666666666666666, 0.041666666666666664, 0.008333333333333333, 0.001388888888888889, 0.0001984126984126984, 2.48015873015873e-5, 2.7557319223985893e-6, 2.755731922398589e-7, 2.505210838544172e-8, 2.08767569878681e-9, 1.6059043836821613e-10, 1.1470745597729725e-11, 7.647163731819816e-13, 4.779477332387385e-14, 2.8114572543455206e-15, 1.5619206968586225e-16, 8.22063524662433e-18, 4.110317623312165e-19, 1.9572941063391263e-20, 8.896791392450574e-22, 3.868170170630684e-23, 1.6117375710961184e-24, 6.446950284384474e-26, 2.4795962632247976e-27, 9.183689863795546e-29, 3.279889237069838e-30, 1.1309962886447716e-31, 3.7699876288159054e-33]
eps_4_1_1 = 1.0e-12

# Case 4.1.3 -- P = 1/(1 - z/2); pole at z = 2.
# Source: Polynomials.roots([1.0, -0.5]).
roots_4_1_3 = ComplexF64[2.0 + 0.0im]
step_4_1_3_expected = 2.0

# Case 4.1.4 -- P = 1/(1 + (z - 3)^2); poles at z = 3 ± i.
# Source: Polynomials.roots([1.0, -0.6, 0.1]) (b normalized so b[1] = 1).
roots_4_1_4 = ComplexF64[3.0 - 1.0000000000000007im, 3.0 + 1.0000000000000007im]
step_4_1_4_expected = 3.0
