# test/corpus_special_fn_test.jl
#
# ============================================================================
# Ground-truth corpus: SPECIAL-FUNCTION IVPs for the core Padé-Taylor stepper
# (bead padetaylor-h5ho, epic padetaylor-p1v0).
#
# WHAT THIS FILE PINS
# -------------------
# Four classical second-order linear ODEs whose solutions are named special
# functions with mpmath natives — an independent accuracy probe of the CORE
# IVP stepper (solve_pade / path_network_solve), distinct from the Heun
# wrapper.  Each oracle is mpmath at 50 dps (no self-reference):
#
#   CSF.1  airy-ivp        u'' = z u,            u = Ai(z)          (entire)
#   CSF.2  bessel-j0-ivp   u'' + u'/z + u = 0,   u = J_0(z)         (IC at z=1)
#   CSF.3  gauss-2f1-ivp   z(1-z)u'' + [5/4-(11/6)z]u' - (1/6)u = 0,
#                          u = 2F1(1/2,1/3;5/4;z)
#   CSF.4  2f1-elementary  F(1/2,3;3;z) = (1-z)^(-1/2)   (DLMF 15.4.6; pole@1)
#
# GROUND TRUTH each embodies:
#   Constants in test/_oracle_corpus_heun.jl, regenerated by
#   external/probes/corpus-oracles/heun/capture.py (mpmath.airyai, .besselj,
#   .hyp2f1; dps=50).  CSF.4 additionally asserts the elementary identity
#   F(1/2,3;3;z) == (1-z)^(-1/2) (verified in capture.py to 50 digits).
#
# CONSTRUCTION caveat (Law 1, documented not hidden):
#   The 2F1 ODEs (CSF.3, CSF.4) have a REGULAR SINGULAR POINT at z=0 — the
#   leading coefficient z(1-z) vanishes there, so f(z,u,up) = (...)/(z(1-z))
#   blows up at the IC point.  Starting the Padé-Taylor jet AT z=0 is
#   ill-posed (it gives wrong values — verified: z=0-start yields 1.081 vs
#   true 1.066 at z=0.4).  We therefore seed the IVP at z0 = 0.05 with the
#   exact series IC (the analytic 2F1 / (1-z)^(-1/2) value there), which is
#   the correct way to pose a Frobenius IVP and mirrors heun_g's own
#   epsilon_start=0.05 strategy (src/Heun.jl).  Airy/Bessel have NO singular
#   point at the IC and start at the catalogue IC directly.
#
# TOLERANCES justified by METHOD, never fitted:
#   * Airy/Bessel (entire, no nearby singularity): the stepper reaches its
#     Float64 (15,15)-Padé floor ~1e-13..1e-14 over [0,3] / [1,5].  Pin 1e-11.
#   * Airy z<0 via path_network_solve (complex-direction single h=0.5 walk):
#     ~1e-12; pin 1e-10.
#   * 2F1 IVPs approach the branch point at z=1: z<=0.7 reaches ~1e-12 (pin
#     1e-10); z=0.9 crowds the branch point and loosens to ~1e-8 (pin 1e-7).
#
# MUTATION-PROOF (Rule 4): footer — a deliberate IC perturbation reddened the
# value assertions; restored byte-clean.
# ============================================================================

using Test
using PadeTaylor

include(joinpath(@__DIR__, "_oracle_corpus_heun.jl"))

@testset "Corpus: special-function IVPs (CSF)" begin

    # ----------------------------------------------------------------------
    # CSF.1  airy-ivp : u'' = z u, u = Ai(z).  Entire; IC at z=0.
    # ----------------------------------------------------------------------
    @testset "CSF.1  Airy u''=zu, u=Ai(z)" begin
        fairy(z, u, up) = z * u
        # Positive real axis via solve_pade (z increasing).
        prob = PadeTaylorProblem(fairy, (AIRY_AI0, AIRY_AIP0), (0.0, 3.0); order = 30)
        sol  = solve_pade(prob; h_max = 0.5)
        @test isapprox(sol(1.0)[1], AIRY_Z1; rtol = 1e-11)
        @test isapprox(sol(2.0)[1], AIRY_Z2; rtol = 1e-11)
        @test isapprox(sol(3.0)[1], AIRY_Z3; rtol = 1e-11)
        # Negative real axis via path_network_solve (solve_pade is z-increasing
        # only; the complex-direction walker handles the reversed segment).
        proba = PadeTaylorProblem(fairy,
                                  (complex(AIRY_AI0), complex(AIRY_AIP0)),
                                  (complex(0.0), complex(-2.0)); order = 30)
        sola = path_network_solve(proba, [complex(-1.0), complex(-2.0)];
                                  h = 0.5, order = 30)
        @test isapprox(real(eval_at(sola, complex(-1.0))[1]), AIRY_ZM1; rtol = 1e-10)
        @test isapprox(real(eval_at(sola, complex(-2.0))[1]), AIRY_ZM2; rtol = 1e-10)
    end

    # ----------------------------------------------------------------------
    # CSF.2  bessel-j0-ivp : u'' + u'/z + u = 0, u = J_0(z).  IC at z=1
    # (avoids the regular singular point at z=0).
    # ----------------------------------------------------------------------
    @testset "CSF.2  Bessel u''+u'/z+u=0, u=J_0(z)" begin
        fbes(z, u, up) = -up / z - u
        prob = PadeTaylorProblem(fbes, (BESSEL_J0_1, -BESSEL_J1_1), (1.0, 5.0); order = 30)
        sol  = solve_pade(prob; h_max = 0.5)
        @test isapprox(sol(2.0)[1], BESSEL_J0_2; rtol = 1e-11)
        @test isapprox(sol(3.0)[1], BESSEL_J0_3; rtol = 1e-11)   # past first zero
        @test isapprox(sol(5.0)[1], BESSEL_J0_5; rtol = 1e-11)   # past second zero
    end

    # ----------------------------------------------------------------------
    # CSF.3  gauss-2f1-ivp : u = 2F1(1/2,1/3;5/4;z).  Seeded at z0=0.05.
    # ----------------------------------------------------------------------
    @testset "CSF.3  Gauss 2F1 IVP, u=2F1(1/2,1/3;5/4;z)" begin
        fg(z, u, up) = (-(5/4 - (11/6)*z)*up + (1/6)*u) / (z*(1-z))
        prob = PadeTaylorProblem(fg, (GAUSS2F1_U0_005, GAUSS2F1_UP0_005),
                                 (0.05, 0.9); order = 30)
        sol  = solve_pade(prob; h_max = 0.45)
        @test isapprox(sol(0.4)[1], GAUSS2F1_Z0p4; rtol = 1e-10)
        @test isapprox(sol(0.7)[1], GAUSS2F1_Z0p7; rtol = 1e-10)
        # z=0.9 crowds the branch point at z=1 → 1e-7.
        @test isapprox(sol(0.9)[1], GAUSS2F1_Z0p9; rtol = 1e-7)
    end

    # ----------------------------------------------------------------------
    # CSF.4  2f1-elementary-reduction : F(1/2,3;3;z) = (1-z)^(-1/2).
    # Cleanest accuracy oracle + algebraic branch point at z=1.
    # ----------------------------------------------------------------------
    @testset "CSF.4  2F1 elementary: F(1/2,3;3;z)=(1-z)^(-1/2)" begin
        # Assert the reduction identity itself (independent of the stepper):
        @test isapprox((1 - 0.4)^(-0.5), 1.29099444873580562839; rtol = 1e-13)
        @test isapprox((1 - 0.9)^(-0.5), 3.16227766016837933200; rtol = 1e-13)
        fe(z, u, up) = (-(3 - (3+1/2+1)*z)*up + 3*(1/2)*u) / (z*(1-z))
        prob = PadeTaylorProblem(fe, (F2F1ELEM_U0_005, F2F1ELEM_UP0_005),
                                 (0.05, 0.9); order = 30)
        sol  = solve_pade(prob; h_max = 0.45)
        @test isapprox(sol(0.4)[1], (1 - 0.4)^(-0.5); rtol = 1e-10)
        # z=0.9 crowds the algebraic branch point at z=1 → 1e-7.
        @test isapprox(sol(0.9)[1], (1 - 0.9)^(-0.5); rtol = 1e-7)
    end
end

# ============================================================================
# MUTATION-PROOF PROCEDURE (Rule 4) — ACTUALLY EXECUTED, then restored.
#
# M-impl (core stepper): in src/PadeStepper.jl `_evaluate_pade`, multiply the
#   numerator constant term by 1.0000001 (1e-7 relative perturbation of the
#   stored Padé).  RESULT: every CSF value assertion that routes through the
#   stored Padé went RED — CSF.1 (Airy z=1/2/3, z=-1/-2), CSF.2 (Bessel
#   2/3/5), CSF.3 (2F1 0.4/0.7), CSF.4 (0.4) — confirming each pins the
#   stepper's Padé, not a tautology.  Restored src/PadeStepper.jl byte-for-
#   byte (`git diff src` empty); suite GREEN.
#
# M-oracle (CSF.2): pin J_0(2) to +0.30 (wrong) instead of 0.22389...  RESULT:
#   CSF.2's z=2 assertion went RED and only there.  Restored.
#
# Run standalone with:
#   julia --project=. test/corpus_special_fn_test.jl
# ============================================================================
