# test/oracle_provenance_test.jl — ORACLE PROVENANCE CONTRACT
#                                  (bead padetaylor-krgy.9, Tier-1 §2.6)
#
# ## Why this file exists — provenance as an ENFORCED contract, not lore
#
# The corpus is anchored by ~25 `test/_oracle_*.jl` files: flat lists of
# pinned literals (closed-form values, mpmath/Mathematica/sympy captures,
# exact rationals) that the `_test.jl` bodies assert against.  A pinned
# literal is only trustworthy if a future reader can answer two questions
# WITHOUT archaeology:
#
#   1. SOURCE      — where did this number come from?  (closed form? an
#                    mpmath dps=50 capture?  an exact rational?  a FORTRAN
#                    reference impl?)  Rule 5: an oracle whose source is
#                    unknown cannot certify anything.
#   2. REGENERATION — how do I re-derive or re-capture it, so the diff is
#                    auditable when the oracle changes?  (which capture
#                    script / verify.jl / closed-form one-liner?)  This is
#                    the krgy.9 snapshot-approval discipline: regenerate →
#                    review `git diff` → approve-commit.
#
# The well-formed oracle files ALREADY answer both — most carry a rich
# `REGENERATION ORACLE:` / `Generated by:` / `PROVENANCE` header naming a
# `external/probes/.../capture.{py,wl,m,jl}` script and a ground-truth
# class.  This test promotes that *de facto* convention into an *enforced*
# contract (Rule 9: a doc nobody checks rots; a test that goes RED does
# not).  It is the executable companion to the runbook
# `docs/test_corpus/04_snapshot_approval_workflow.md`.
#
# ## The contract this test asserts (the convention, verbatim)
#
# For every `test/_oracle*.jl` data file, its LEADING COMMENT HEADER
# (the contiguous `#`-comment block at the top, before the first code
# line) must contain BOTH, non-empty:
#
#   * a SOURCE marker — naming the ground-truth class.  Any of:
#       closed-form · exact rational/algebraic · mpmath · Mathematica /
#       wolfram / NDSolve · sympy · scipy · TaylorIntegration · DMSUITE ·
#       padeapprox.m · Calgo / FORTRAN · DLMF · binomial · PROVENANCE.
#   * a REGENERATION marker — naming how to re-derive.  Any of:
#       a capture-script path (`capture.py|.wl|.m|.jl`, `verify.jl`) OR an
#       explicit regen phrase (`REGENERATION ORACLE`, `Generated by`,
#       `auto-generated by`, `regenerate`, `re-run`/`Re-run`, `PROVENANCE`).
#
# This is a REAL invariant (Rule 5): the markers must be PRESENT and the
# header NON-TRIVIAL (≥ 3 comment lines, ≥ 80 chars of prose) — not
# "the file parsed".  Blank a marker out of any header and this test
# goes RED (mutation-proof in the footer).
#
# ## Scope + survey result (2026-06-09)
#
# Globbed `test/_oracle*.jl` → 25 files.  At authoring time ALL 25 comply:
# the 24 `_oracle_*.jl` corpus files each carry a `REGENERATION ORACLE:` /
# `Generated by:` / `PROVENANCE` header, and `_oracles.jl` (the original
# padeapprox.m Padé literals) was brought up to convention in the SAME
# session with a minimal, accurate header naming
# `external/probes/padeapprox-oracle/capture.m`.  See the runbook for the
# regenerate→review→approve flow each header documents.
#
# References:
#   - docs/test_corpus/04_snapshot_approval_workflow.md  (the runbook)
#   - docs/test_corpus/03_hardening_methodology.md:148-152 (Tier §2.6)
#   - docs/test_corpus/00_capability_map.md  B22 (oracle-regeneration theme)
#   - test/accuracy_baseline.toml + test/accuracy_ledger_test.jl (the
#     worked regeneration-via-env-var example krgy.9 generalises)
#   - bd show padetaylor-krgy.9                              (the bead)
#
# Mutation-proof procedure recorded in the file footer (Rule 4).

using Test

const _ORACLE_DIR = @__DIR__

# The oracle DATA files: flat pinned-literal lists, named `_oracle*.jl`.
# (`_test.jl` files carry test LOGIC, not pinned data, and are excluded —
# their provenance lives in the data files they `include`.)
_oracle_data_files() =
    sort(filter(f -> startswith(f, "_oracle") && endswith(f, ".jl"),
                readdir(_ORACLE_DIR)))

# The LEADING comment header: the contiguous run of `#`-comment / blank
# lines from the top of the file, stopping at the first line of code.
# Blank lines INSIDE the banner are kept (headers use them as spacers);
# the run ends at the first non-blank, non-comment line.
function _leading_header(path::AbstractString)
    io = IOBuffer()
    for line in eachline(path)
        s = lstrip(line)
        if startswith(s, "#") || isempty(strip(line))
            println(io, line)
        else
            break
        end
    end
    return String(take!(io))
end

# A SOURCE marker names the ground-truth CLASS the literals were derived
# from.  Matched case-insensitively; the alternatives are exactly the
# ground-truth vocabulary the corpus already uses (surveyed across all 25
# files).  `\b` on the multi-word forms tolerates "closed form" / "closed-
# form" / "closedform" spellings.
const _SOURCE_MARKERS = Regex(
    "(?i)(" * join([
        "closed[ -]?form",
        "exact[ -]?(rational|algebraic|integer)",
        "mpmath",
        "mathematica|wolfram(script)?|ndsolve|asymptoticdsolve",
        "sympy",
        "scipy",
        "taylorintegration",
        "dmsuite",
        "padeapprox\\.m",
        "calgo|fortran",
        "dlmf",
        "binomial",
        "provenance",
    ], "|") * ")")

# A REGENERATION marker names HOW to re-derive: a capture-script path or an
# explicit regenerate/auto-generated phrase.  This is what makes the golden
# AUDITABLE — a reviewer can re-run it and diff (the krgy.9 discipline).
const _REGEN_MARKERS = Regex(
    "(?i)(" * join([
        "capture\\.(py|wl|m|jl)",
        "verify\\.jl",
        "regeneration oracle",
        "generated by",
        "auto-generated by",
        "regenerate",
        "re-?run",
        "provenance",
    ], "|") * ")")

# Header substance floor: a marker buried in a one-line stub is not a
# provenance block.  Real headers in this corpus run dozens of lines; we
# require a modest minimum so a token alone can't satisfy the contract.
const _MIN_HEADER_LINES = 3
const _MIN_HEADER_CHARS = 80

@testset "Oracle provenance contract (bead padetaylor-krgy.9)" begin
    files = _oracle_data_files()

    # The corpus is large and growing; a regression that DELETES every
    # oracle file would vacuously pass an empty loop.  Pin the floor.
    @test length(files) ≥ 20

    @testset "provenance header: $f" for f in files
        header = _leading_header(joinpath(_ORACLE_DIR, f))

        # NON-TRIVIAL header — substance, not a bare token (Rule 5).
        nlines = count(==('\n'), header)
        @test nlines ≥ _MIN_HEADER_LINES
        @test length(strip(header)) ≥ _MIN_HEADER_CHARS

        # SOURCE present + non-empty.
        src = match(_SOURCE_MARKERS, header)
        @test src !== nothing
        @test src === nothing || !isempty(src.match)

        # REGENERATION / derivation reference present + non-empty.
        regen = match(_REGEN_MARKERS, header)
        @test regen !== nothing
        @test regen === nothing || !isempty(regen.match)
    end
end

# ----------------------------------------------------------------------------
# Mutation-proof (CLAUDE.md Rule 4) — performed + VERIFIED 2026-06-09; the
# mutated test data file restored before commit (`git diff test/` clean of
# the mutation, re-confirmed).  This test enforces a PROPERTY of the oracle
# headers, so the proof BLANKS a provenance field and confirms RED:
#
#   SOURCE-side (the headline).  In `test/_oracle_corpus_taylor_jet.jl`,
#   temporarily delete the whole `REGENERATION ORACLE:` paragraph (the lines
#   naming `external/probes/corpus-oracles/taylor-jet/capture.py` AND every
#   `mpmath` / source word) from the leading header.  RESULT (verified):
#   the `provenance header: _oracle_corpus_taylor_jet.jl` subtestset goes
#   RED — BOTH the SOURCE `@test src !== nothing` and the REGENERATION
#   `@test regen !== nothing` fail, because the remaining header (the
#   SHARED-IC paragraph) names neither a ground-truth class nor a capture
#   script.  Restored; `git diff test/` clean; the contract GREEN again.
#
#   SUBSTANCE-side (the floor has teeth, not a tautology).  Replace any
#   oracle file's whole header with a single `# stub` line: the
#   `nlines ≥ 3` / `length ≥ 80` substance asserts go RED even though
#   `# stub` is technically a comment — proving the contract demands a real
#   provenance BLOCK, not merely "starts with #".  Restored.
#
#   COUNT-floor.  Pointing `_oracle_data_files()` at an empty dir (or
#   deleting the files) trips `@test length(files) ≥ 20` — the empty-loop
#   vacuous-pass hole is closed.
#
# All mutations confirmed RED then reverted; no test-data change persisted.
