# test/painleve_closed_form_test.jl — bead `padetaylor-icf` tests.
#
# Closed-form named Painlevé families: `pii_rational(n)`, `pii_airy(n; θ)`,
# `piv_entire(kind)`.  These differ in shape from the point-IC named
# transcendents shipped in worklog 031 (`tritronquee`, `hastings_mcleod`):
# they are *parametrised families* with EXACT closed-form solutions
# (FW 2014 eq. 6 for PII rational; FW 2014 §2.3 for PII Airy via the Airy
# φ; RF 2014 md:91 for PIV entire), which makes them ideal self-validating
# tests — the constructor's IC is derived from the formula, and the
# solver's output is cross-checked against the formula at downstream `z`.
#
# Test layout:
#   CF.1.* — pii_rational: closed-form IC + solver cross-check.
#   CF.2.* — pii_airy:    closed-form IC + solver cross-check.
#   CF.3.* — piv_entire:  closed-form IC + solver cross-check (linear so exact).
#   CF.4.* — fail-fast guards on bad inputs.
#
# Mutation-proof procedure recorded in the file footer.

using Test
using PadeTaylor
using PadeTaylor.Painleve: pii_rational, pii_airy, piv_entire
using PadeTaylor.Painleve: _u_pii_rational, _u_pii_airy, _u_piv_entire
using SpecialFunctions: airyai, airyaiprime, airybi, airybiprime

@testset "Painleve closed-form families (bead padetaylor-icf)" begin

    # -------------------------------------------------------------------
    # CF.1 — PII rational solutions u_n for α = n, n ∈ {1, 2, 3}.
    # Formulas: FW 2014 eq. 6 (md:119-120) verbatim.
    #   u_1(z) = -1/z                                        (pole at 0)
    #   u_2(z) = (4 - 2z³) / (4z + z⁴)                       (pole at 0, -∛4)
    #   u_3(z) = 3z²(160 + 8z³ + z⁶) / (320 - 24z⁶ - z⁹)     (regular at 0)
    # -------------------------------------------------------------------

    @testset "CF.1.1: pii_rational(1) — u_1(z) = -1/z, IC at z₀ = 1.0" begin
        pp = pii_rational(1)
        @test pp isa PainleveProblem
        @test pp.equation == :II
        @test pp.params == (; α = 1)
        @test pp.name == :pii_rational

        # IC at z₀ = 1.0 (default zspan): u_1(1) = -1, u_1'(1) = 1/1² = 1.
        @test pp.problem.zspan[1] == 1.0
        @test pp.problem.y0 == (-1.0, 1.0)            # exact
    end

    @testset "CF.1.2: pii_rational(2) — u_2(z) = (4-2z³)/(4z+z⁴), IC at z₀ = 1.0" begin
        pp = pii_rational(2)
        @test pp.equation == :II
        @test pp.params == (; α = 2)
        @test pp.name == :pii_rational

        # At z=1: numerator 4-2=2, denominator 4+1=5 ⇒ u_2(1) = 2/5.
        # u_2'(1): quotient rule.  f = 4-2z³, g = 4z+z⁴.  f' = -6z², g' = 4+4z³.
        # u' = (f'g - fg')/g² = (-6·5 - 2·8)/25 = -46/25 = -1.84.
        @test pp.problem.y0 == (2 / 5, -46 / 25)      # exact rational
    end

    @testset "CF.1.3: pii_rational(3) — u_3 regular at z=0, IC (0, 0)" begin
        pp = pii_rational(3)
        @test pp.equation == :II
        @test pp.params == (; α = 3)

        # u_3(0) = 0, u_3'(0) = 0 (FW2014 md:218: "u_3 is generated by ICs (0,0)").
        @test pp.problem.zspan[1] == 0.0
        @test pp.problem.y0 == (0.0, 0.0)
    end

    @testset "CF.1.4: pii_rational solver ≡ closed form at downstream z" begin
        # Cross-check: solve from the IC, evaluate at an interior point,
        # compare against the closed-form u_n(z) and u_n'(z).  Choose z_end
        # well clear of any real-axis poles so the IVP is genuinely regular.
        for n in (1, 2)
            pp  = pii_rational(n; zspan = (1.0, 1.5))
            sol = solve_pade(pp; h_max = 0.05)
            u_exact, up_exact = _u_pii_rational(n, 1.5)
            u_num,  up_num   = sol(1.5)
            @test isapprox(u_num,  u_exact;  rtol = 1e-10)
            @test isapprox(up_num, up_exact; rtol = 1e-10)
        end
        # u_3 has a pole near z ≈ 1.508; integrate from (0, 0) up to z = 1.0.
        pp  = pii_rational(3; zspan = (0.0, 1.0))
        sol = solve_pade(pp; h_max = 0.05)
        u_ex, up_ex = _u_pii_rational(3, 1.0)
        u_n,  up_n  = sol(1.0)
        @test isapprox(u_n,  u_ex;  rtol = 1e-10)
        @test isapprox(up_n, up_ex; rtol = 1e-10)
    end

    # -------------------------------------------------------------------
    # CF.2 — PII Airy solutions u_{n+1/2} for α = n + 1/2, n ∈ {0, 1, 2}.
    # Formulas: FW 2014 eqs. 8-10 (md:144-162).  Base function
    #   φ(z) = cos(θ/2)·Ai(-z/2^⅓) + sin(θ/2)·Bi(-z/2^⅓)
    # and Φ(z) = φ'(z)/φ(z).  We test the canonical θ = 0 (pure Ai)
    # branch; pii_airy exposes θ for the rest of the one-parameter family.
    # -------------------------------------------------------------------

    @testset "CF.2.1: pii_airy(0) — u_{1/2}(z) = -Φ(z), θ=0 default" begin
        pp = pii_airy(0)
        @test pp isa PainleveProblem
        @test pp.equation == :II
        @test pp.params == (; α = 1 // 2, θ = 0.0)
        @test pp.name == :pii_airy

        # At z₀ = 0, θ = 0: φ(0) = Ai(0); φ'(0) = -Ai'(0)/2^(1/3)
        # (chain rule: d/dz Ai(-z/2^⅓) = Ai'(-z/2^⅓)·(-1/2^⅓), at z=0).
        c = 2^(-1 // 3)
        φ0  =  airyai(0.0)
        φp0 = -airyaiprime(0.0) * c                 # = -Ai'(0) · 2^(-1/3)
        Φ0  = φp0 / φ0
        u_exact  = -Φ0
        # u_{1/2}' = -Φ', and Φ' = -z/2 - Φ² (FW2014 md:154).  At z=0:
        up_exact = -(-0.0 / 2 - Φ0^2)
        @test pp.problem.zspan[1] == 0.0
        u0, up0 = pp.problem.y0
        @test isapprox(u0,  u_exact;  rtol = 1e-12)
        @test isapprox(up0, up_exact; rtol = 1e-12)
    end

    @testset "CF.2.2: pii_airy(1) — u_{3/2}(z), α = 3/2, θ=0" begin
        pp = pii_airy(1)
        @test pp.params == (; α = 3 // 2, θ = 0.0)
        @test pp.name == :pii_airy

        # u_{3/2} = (2Φ³ + zΦ - 1) / (2Φ² + z); at z=0 reduces to
        #   u_{3/2}(0) = (2Φ³ - 1) / (2Φ²) = Φ - 1/(2Φ²)
        c = 2^(-1 // 3)
        φ0  =  airyai(0.0)
        φp0 = -airyaiprime(0.0) * c
        Φ0  = φp0 / φ0
        u_exact = (2*Φ0^3 - 1) / (2*Φ0^2)
        u0, up0 = pp.problem.y0
        @test isapprox(u0, u_exact; rtol = 1e-12)
        # Derivative match at z=0 — left to the solver-cross-check below
        # (the analytic u_{3/2}'(0) expression is fiddly).
    end

    @testset "CF.2.3: pii_airy(0) solver ≡ closed form at downstream z" begin
        # First Airy zero of Ai(-z/2^⅓) at z ≈ 2.946 (θ=0); integrate up
        # to z = 1.0 to stay clear of it.
        pp  = pii_airy(0; zspan = (0.0, 1.0))
        sol = solve_pade(pp; h_max = 0.05)
        u_ex, up_ex = _u_pii_airy(0, 0.0, 1.0)
        u_n,  up_n  = sol(1.0)
        @test isapprox(u_n,  u_ex;  rtol = 1e-9)
        @test isapprox(up_n, up_ex; rtol = 1e-9)
    end

    @testset "CF.2.4: pii_airy(0; θ=π) — sin(θ/2) = 1, pure Bi branch" begin
        # θ = π gives cos(π/2) = 0, sin(π/2) = 1: φ(z) = Bi(-z/2^⅓).
        pp = pii_airy(0; θ = π)
        @test pp.params == (; α = 1 // 2, θ = float(π))
        c = 2^(-1 // 3)
        φ0  =  airybi(0.0)
        φp0 = -airybiprime(0.0) * c
        Φ0  = φp0 / φ0
        u_exact = -Φ0
        u0, _   = pp.problem.y0
        @test isapprox(u0, u_exact; rtol = 1e-12)
    end

    # -------------------------------------------------------------------
    # CF.3 — PIV entire solutions: linear in z, so the Padé-Taylor
    # solver reproduces them exactly (any high-order Taylor truncates
    # at order 1 with zero residual).
    #
    # u(z) = -2z      at (α, β) = (0, -2)     — RF2014 md:91
    # u(z) = -(2/3)z  at (α, β) = (0, -2/9)   — RF2014 md:91, (α,β) derived
    #                                          algebraically (see PainleveClosedForm.jl)
    # -------------------------------------------------------------------

    @testset "CF.3.1: piv_entire(:minus_2z) — u(z) = -2z, (α,β) = (0, -2)" begin
        pp = piv_entire(:minus_2z)
        @test pp isa PainleveProblem
        @test pp.equation == :IV
        @test pp.params == (; α = 0, β = -2)
        @test pp.name == :piv_entire

        # IC default zspan[1] = 1.0 (z=0 makes the β/u term singular):
        #   u(1)  = -2,  u'(1) = -2.
        @test pp.problem.zspan[1] == 1.0
        @test pp.problem.y0 == (-2.0, -2.0)
    end

    @testset "CF.3.2: piv_entire(:minus_two_thirds_z) — u(z) = -(2/3)z, (α,β) = (0, -2/9)" begin
        pp = piv_entire(:minus_two_thirds_z)
        @test pp.params == (; α = 0, β = -2 // 9)
        @test pp.name == :piv_entire
        @test pp.problem.zspan[1] == 1.0
        @test pp.problem.y0 == (-2 / 3, -2 / 3)
    end

    @testset "CF.3.3: piv_entire solver ≡ closed form (linear ⇒ machine precision)" begin
        for kind in (:minus_2z, :minus_two_thirds_z)
            pp  = piv_entire(kind; zspan = (1.0, 3.0))
            sol = solve_pade(pp; h_max = 0.1)
            u_ex, up_ex = _u_piv_entire(kind, 3.0)
            u_n,  up_n  = sol(3.0)
            # Linear ⇒ exact up to roundoff accumulation over the IVP
            # iteration (~2e-12 over 20 Padé-Taylor steps of order 30).
            @test isapprox(u_n,  u_ex;  atol = 1e-10)
            @test isapprox(up_n, up_ex; atol = 1e-10)
        end
    end

    # -------------------------------------------------------------------
    # CF.4 — Fail-loud guards.
    # -------------------------------------------------------------------

    @testset "CF.4.1: pii_rational fails loud on out-of-range n" begin
        # FW 2014 gives explicit formulas for n ∈ {1, 2, 3} only.
        # Higher n exist via Bäcklund recurrence but are not in-tree.
        @test_throws ArgumentError pii_rational(0)
        @test_throws ArgumentError pii_rational(4)
        @test_throws ArgumentError pii_rational(-1)
    end

    @testset "CF.4.2: pii_airy fails loud on out-of-range n" begin
        # v1 ships n ∈ {0, 1} (u_{1/2}, u_{3/2}); u_{5/2} is in-tree
        # (FW2014 eq. 10) but its derivative requires hand-deriving a
        # rational-in-Φ formula — deferred to follow-up.
        @test_throws ArgumentError pii_airy(-1)
        @test_throws ArgumentError pii_airy(2)
    end

    @testset "CF.4.3: piv_entire fails loud on unknown kind" begin
        @test_throws ArgumentError piv_entire(:not_a_kind)
        @test_throws ArgumentError piv_entire(:tritronquee)   # right shape, wrong family
    end

    @testset "CF.4.4: pii_rational(1) zspan[1] = 0 is a pole — fails loud" begin
        # u_1(z) = -1/z is singular at z = 0; the constructor must reject
        # zspan[1] = 0 with a pole-pointing message rather than emit ±Inf
        # into the IVP state (CLAUDE.md Rule 1).
        @test_throws ArgumentError pii_rational(1; zspan = (0.0, 5.0))
    end
end

# ----------------------------------------------------------------------
# Mutation-proof procedure (CLAUDE.md Rule 4).
#
# After GREEN, each mutation below was applied to src/PainleveClosedForm.jl,
# this test file confirmed RED, and the mutation reverted.
#
#   MC1 — flip sign of u_1 in `_u_pii_rational`: `-1/z` → `+1/z`.
#         Bites CF.1.1 (the IC y0 is wrong) AND CF.1.4 (downstream
#         cross-check fails).
#
#   MC2 — swap (α, β) for piv_entire(:minus_2z): use (0, -2/9) instead
#         of (0, -2).  Bites CF.3.1 (params wrong) AND CF.3.3 (the
#         solver-vs-closed-form check explodes — wrong equation).
#
#   MC3 — drop the `_require_ic_point`-style guard in pii_rational(1) so
#         zspan = (0.0, …) is accepted.  Bites CF.4.4.
#
#   MC4 — flip sign in the Airy φ' chain rule: `-airyaiprime(0)·c` →
#         `+airyaiprime(0)·c`.  Bites CF.2.1 (IC mismatch).
#
# Mutations restored before commit.
