using Test
using PadeTaylor

@testset "PadeTaylor.jl" begin
    @testset "umbrella loads" begin
        # Confirms the umbrella module + its 8 sub-modules load cleanly.
        @test isdefined(PadeTaylor, :LinAlg)
        @test isdefined(PadeTaylor, :RobustPade)
        @test isdefined(PadeTaylor, :SharedPade)
        @test isdefined(PadeTaylor, :Coefficients)
        @test isdefined(PadeTaylor, :VectorCoefficients)
        @test isdefined(PadeTaylor, :StepControl)
        @test isdefined(PadeTaylor, :PadeStepper)
        @test isdefined(PadeTaylor, :VectorStepper)
        @test isdefined(PadeTaylor, :VectorStepControl)
        @test isdefined(PadeTaylor, :VectorProblems)
        @test isdefined(PadeTaylor, :VectorBVP)
        @test isdefined(PadeTaylor, :NoumiYamada)
        @test isdefined(PadeTaylor, :NoumiYamadaSymmetry)
        @test isdefined(PadeTaylor, :PainleveHierarchy)
        @test isdefined(PadeTaylor, :VectorPathNetwork)
        @test isdefined(PadeTaylor, :VectorPoleField)
        @test isdefined(PadeTaylor, :Problems)
        @test isdefined(PadeTaylor, :PathNetwork)
        @test isdefined(PadeTaylor, :BVP)
        @test isdefined(PadeTaylor, :Dispatcher)
        @test isdefined(PadeTaylor, :EdgeDetector)
        @test isdefined(PadeTaylor, :LatticeDispatcher)
        @test isdefined(PadeTaylor, :CoordTransforms)
        @test isdefined(PadeTaylor, :Laplace2D)
        @test isdefined(PadeTaylor, :SheetTracker)
        @test isdefined(PadeTaylor, :BranchTracker)
        @test isdefined(PadeTaylor, :Painleve)
        @test isdefined(PadeTaylor, :IVPBVPHybrid)
    end

    # Per-module test files. Each file is a self-contained @testset.
    # Phases 1–6 + Phase 10 PathNetwork + Phase 11 BVP + Phase 12
    # Dispatcher fill in these.
    include("linalg_test.jl")
    include("robustpade_test.jl")
    include("shared_pade_test.jl")
    include("shared_pade_dispatch_test.jl")
    include("classical_pade_test.jl")
    include("coefficients_test.jl")
    include("vector_coefficients_test.jl")
    include("stepcontrol_test.jl")
    include("padestepper_test.jl")
    include("vector_stepper_test.jl")
    include("vector_step_control_test.jl")
    include("vector_problems_test.jl")
    include("noumi_yamada_test.jl")
    include("noumi_yamada_symmetry_test.jl")
    # Metamorphic-relation test layer (oracle-free invariants), bead
    # padetaylor-krgy.3.  Symmetry MRs (conjugate, PII α-negation, PIV parity)
    # + consistency MRs (step additivity, forward∘reverse).  The canonical
    # algebraic NY Bäcklund MR lives in noumi_yamada_symmetry_test.jl (NYS.1.6).
    include("metamorphic_symmetry_test.jl")
    include("metamorphic_consistency_test.jl")
    include("noumi_yamada_piv_test.jl")
    include("painleve_hierarchy_test.jl")
    include("vector_path_network_test.jl")
    include("vector_path_network_stage2_test.jl")
    include("calogero_moser_test.jl")
    include("problems_test.jl")
    include("corpus_scalar_pole_bridge_test.jl")
    include("corpus_robust_pade_test.jl")
    include("corpus_taylor_jet_test.jl")
    include("corpus_vector_test.jl")
    include("corpus_vector_polefield_test.jl")
    include("corpus_bvp_test.jl")
    include("corpus_bvp_hybrid_test.jl")
    include("corpus_morphology_test.jl")
    include("corpus_multisheet_test.jl")
    include("corpus_winding_test.jl")
    include("corpus_painleve_rational_test.jl")
    include("corpus_noumi_yamada_test.jl")
    include("pathnetwork_test.jl")
    include("branch_tracker_test.jl")
    include("path_network_branch_test.jl")
    include("sheet_aware_stage2_test.jl")
    include("extrapolate_test.jl")
    include("adaptive_step_test.jl")
    include("non_uniform_nodes_test.jl")
    include("polefield_test.jl")
    include("bvp_test.jl")
    include("dispatcher_test.jl")
    include("edge_detector_test.jl")
    include("laplace2d_test.jl")
    include("phase9_tritronquee_test.jl")
    include("lattice_dispatcher_test.jl")
    include("edge_gated_solve_test.jl")
    include("ext_commonsolve_test.jl")
    include("ext_arblib_test.jl")
    include("ext_makie_test.jl")
    # Certified ball oracles (Arblib midpoint-radius), bead padetaylor-krgy.5.
    # Tier-2 §2.2: certifies the closed-form Weierstrass-℘ ORACLE as a
    # provably-tiny Arb ball (radius < ε_cert), THEN pins the package's
    # solve_pade value to that ball's midpoint at the package tolerance
    # (tol_pkg ≫ ε_cert).  Certifies the oracle side, NOT the SVD output
    # (Arblib has no SVD; ADR-0002).  See docs/adr/0029-certified-ball-oracles.md.
    include("certified_oracle_test.jl")
    # Static-analysis + lint quality gate (Aqua/JET/ExplicitImports), bead
    # padetaylor-krgy.2.  Infra-tier: asserts package hygiene + abstract-
    # interpretation cleanliness, not a numerical invariant.
    include("quality_test.jl")
    # Property-based invariant gate (Supposition.jl), bead padetaylor-krgy.1.
    # Tier-1 §1.2: generates hundreds of inputs per property and shrinks
    # failures to a minimal counterexample; pins INVARIANTS where the corpus
    # pins VALUES.
    include("property_test.jl")
    include("diagnose_test.jl")
    include("fw_fig_41_test.jl")
    include("coord_transforms_test.jl")
    include("sheet_tracker_test.jl")
    include("eta_pvi_test.jl")
    include("painleve_test.jl")
    include("painleve_solution_test.jl")
    include("painleve_named_test.jl")
    include("painleve_closed_form_test.jl")
    include("ffw_fig_6_test.jl")
    include("ffw_fig_1_test.jl")
    include("ffw_fig_4_test.jl")
    include("ivp_bvp_hybrid_test.jl")
    include("ffw_fig_5_test.jl")
    include("ffw_fig_2_test.jl")
    include("ffw_fig_3_test.jl")
    include("ffw_fig_7_test.jl")
    include("noumi_yamada_a4_figure_test.jl")
    include("kkg_pi2_figure_test.jl")
    include("vector_bvp_test.jl")
    include("vector_bvp_wirein_test.jl")
    include("corpus_vector_bvp_test.jl")
    include("vector_pipeline_oracle_test.jl")
    include("heun_test.jl")
    include("corpus_heun_test.jl")
    include("corpus_special_fn_test.jl")
    include("corpus_riccati_rational_test.jl")
    include("corpus_riccati_special_test.jl")
    include("corpus_periodic_pole_test.jl")
    include("corpus_orthopoly_bvp_test.jl")
    include("corpus_special_fn_bvp_test.jl")
    include("corpus_oblique_guard_test.jl")
    include("corpus_higher_order_pole_test.jl")
    include("corpus_elliptic_lattice_test.jl")
    include("corpus_elementary_branch_test.jl")
    include("corpus_pathnet_walls_rows_test.jl")
    include("corpus_pathnet_lattice_sectors_test.jl")
    include("corpus_pathnet_winding_test.jl")
    include("corpus_algebraic_pvi_test.jl")
    include("corpus_out_of_class_test.jl")
end
