using Test
using PadeTaylor

@testset "PadeTaylor.jl" begin
    @testset "umbrella loads" begin
        # Confirms the umbrella module + its 8 sub-modules load cleanly.
        @test isdefined(PadeTaylor, :LinAlg)
        @test isdefined(PadeTaylor, :RobustPade)
        @test isdefined(PadeTaylor, :Coefficients)
        @test isdefined(PadeTaylor, :StepControl)
        @test isdefined(PadeTaylor, :PadeStepper)
        @test isdefined(PadeTaylor, :Problems)
        @test isdefined(PadeTaylor, :PathNetwork)
        @test isdefined(PadeTaylor, :BVP)
        @test isdefined(PadeTaylor, :Dispatcher)
        @test isdefined(PadeTaylor, :EdgeDetector)
        @test isdefined(PadeTaylor, :LatticeDispatcher)
        @test isdefined(PadeTaylor, :CoordTransforms)
        @test isdefined(PadeTaylor, :SheetTracker)
        @test isdefined(PadeTaylor, :BranchTracker)
        @test isdefined(PadeTaylor, :Painleve)
        @test isdefined(PadeTaylor, :IVPBVPHybrid)
    end

    # Per-module test files. Each file is a self-contained @testset.
    # Phases 1–6 + Phase 10 PathNetwork + Phase 11 BVP + Phase 12
    # Dispatcher fill in these.
    include("linalg_test.jl")
    include("robustpade_test.jl")
    include("classical_pade_test.jl")
    include("coefficients_test.jl")
    include("stepcontrol_test.jl")
    include("padestepper_test.jl")
    include("problems_test.jl")
    include("pathnetwork_test.jl")
    include("branch_tracker_test.jl")
    include("path_network_branch_test.jl")
    include("sheet_aware_stage2_test.jl")
    include("extrapolate_test.jl")
    include("adaptive_step_test.jl")
    include("non_uniform_nodes_test.jl")
    include("polefield_test.jl")
    include("bvp_test.jl")
    include("dispatcher_test.jl")
    include("edge_detector_test.jl")
    include("phase9_tritronquee_test.jl")
    include("lattice_dispatcher_test.jl")
    include("edge_gated_solve_test.jl")
    include("ext_commonsolve_test.jl")
    include("ext_arblib_test.jl")
    include("ext_makie_test.jl")
    include("fw_fig_41_test.jl")
    include("coord_transforms_test.jl")
    include("sheet_tracker_test.jl")
    include("eta_pvi_test.jl")
    include("painleve_test.jl")
    include("painleve_solution_test.jl")
    include("painleve_named_test.jl")
    include("painleve_closed_form_test.jl")
    include("ffw_fig_6_test.jl")
    include("ffw_fig_1_test.jl")
    include("ffw_fig_4_test.jl")
    include("ivp_bvp_hybrid_test.jl")
    include("ffw_fig_5_test.jl")
    include("ffw_fig_2_test.jl")
    include("ffw_fig_3_test.jl")
end
